name: epos4_controller
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake
  - gxx_linux-64 >=14.3.0
  - gcc_linux-64 >=14.3.0
  - sysroot_linux-64 >=2.28
  - make
  - cxx-compiler
  - sysroot_linux-64
  - soem >= 2.0.0
  - clang-tools
